version: '3'

vars:
  BINARY: ./bin/second-year-project

tasks:
  default:
    desc: List the available task commands.
    cmds:
      - task --list-all
    silent: true

  build:
    desc: Build objects & executables from sources.
    cmds:
      - cmake .                     # generate build files
      - cmake --build .             # build project
      - mkdir -p bin
      - mv ./second-year-project {{.BINARY}}

  test:
    desc: Run program tests
    cmds:
      - task build

  run:
    desc: Build and run the project
    cmds:
      - task build
      - "{{.BINARY}}"

  clean:
    desc: Remove generated build outputs
    cmds:
      - rm -rf ./build
      - rm -rf ./bin

  docs:
    desc: Generate documentation for source code
    cmds:
      - doxygen Doxyfile
      - google-chrome ./html/index.html
